### PR TITLE
GRULayer

### PR DESCRIPTION
**Pull request by skaae**
Inital GRU commit and tests

I'll need to clean this up a bit tomorrow.

### CODE REVIEW

**Comment by skaae** [comment]
Waiting for https://github.com/craffel/nntools/pull/34 to be merged.

TODO:  
- Add scan unroll + tests 
- allow for batch and seqlen = None  (Done)

**Comment by craffel** [comment]
So, I'd really like this layer and the `LSTMLayer` to use the same underlying code.  As far as I can tell, they do the same thing except that the `GRULayer` has fewer connections.  I'd like to make it so that if one provides `None` for one of the weight matrices or bias vectors in the `LSTMLayer`, that connection is not included.  That way, the `GRULayer` would just construct an `LSTMLayer` with the appropriate keyword arguments set to `None`.  This way, we could also get rid of the `peepholes` keyword argument and also allow for all of the architectures experimented with in this work: http://arxiv.org/abs/1503.04069  What do you think?  Doing it this way will probably make the code a good bit more complex, but I think it's worthwhile.

**Comment by skaae** [comment]
I think the calculations for LSTM and GRU are so different that it would be hard to share code. 
GRU does not have a seperate cell value. Instead it calculate the new value as a weighted sum of the old hidden value and an updated hidden value:

```
hid = (1-updategate)*hid_previous + updategate*cell
```

All code for calculating the GRU cell value is slightly different, except for calculating the gate values and slicing. I think there might also be a few different GRU implementation. I choose that particular implementation because it could be implemented with a single matrix multiplication.

The `__init__` is different in the size of the weights, the number of weights and in that GRU has no peepholes. `get_output_for` is different at least in the step functions. 

I prefer to keep the layers seperate. In my opinion its a lot easier to read and it's also easier for other people to experiment with the code. I think this is a key difference between lasagne and blocks/pylearn2. In lasagne the layers are fairly simple and easy to modify where as in pylearn2/blocks they seem more complex. I think we should strive to keep things as simple as possible even if we need a little code dublication. 

I you really wanted to couldn''t you then emulate some of the variants with a hacky activation unit that returns an identity matrix or something like that? 

(have you seen that im cited in the http://arxiv.org/abs/1503.04069, whooo :))

And thanks for helping out with TIMIT. If it works i'll add an example with CTC + lasagne.

**Comment by skaae** [comment]
I'll move this PR to the new branch as well.

**Comment by craffel** [comment]
Hmm, yeah, looking at it I think it's possible aside from the fact that the input gate in the GRU is one minus the forget gate, while it''s a separate gate in the GRU.  I believe you could make it work by defining the forget gate activation to be a new function which is 1 - sigmoid, and supplying the same shared variables for the input and forget gates, but that would be pretty inefficient because you'd end up calculating the same value twice.  Beyond that, it would make the code a bit more complex to allow parameters to be set to None to denote "don't compute this connection.

Ok, I'm Ok with this being separate, make a new PR and we'll sort the rest out there

**Comment by skaae** [comment]
I moved the pr here: https://github.com/craffel/nntools/pull/42

**Pull request closed without merging**
