### PR TITLE
Recurrent docs

### PR DESCRIPTION
**Pull request by skaae**
Adds the recureent layers to layers.rst such that the docs build with `make html`

Fixes a few typos / copy pase errors in the docs.

### CODE REVIEW

**Comment by craffel** [comment]
Looks good, thanks.  I actually think we should move away from using the math symbols for the parameter descriptions unless we include the equations in the docstring, but we don't need to address that here.

**Comment by skaae** [comment]
I'm looking into how me include the recurrent "overview" description to the docs. I guess it should have the same look as updates in the lasagne docs?

**Comment by craffel** [comment]
Hm, that's a good question, it's different because `updates` is its own submodule of Lasagne so you can use `.. automodule:: lasagne.updates`.  I'm not sure how to designate that you want the file docstring of a file which is not itself a submodule to be included in the docs, but there must be a way.

**Comment by skaae** [comment]
This seems to work:

```
Layer classes: recurrent layers
-------------------------------

.. automodule:: lasagne.layers.recurrent


.. autoclass:: CustomRecurrentLayer
    :members:

.. autofunction:: RecurrentLayer
    :members:

.. autoclass:: LSTMLayer
    :members:
```

Also makes the docs way easier to read. I think all groups of layers should have such a description.

**Comment by craffel** [comment]
> Also makes the docs way easier to read. I think all groups of layers should have such a description.

You're probably right :) you should make an issue/PR on the main Lasagne branch for that!

**Comment by skaae** [comment]
I think i'll propose it, all the descriptions has to be written :)

btw if you update the rst can you also check that the recrrentLayer link is correct in the file docstring? I think there might be a spelling error in the link.

**Pull request merged**
