### PR TITLE
add step_scaling rule

### PR DESCRIPTION
**Pull request by skaae**
Step scaling based on total norm of gradients + tests

### CODE REVIEW

**Comment by craffel** [comment]
I think this actually could be a PR to the Lasagne master branch, right?  Do you want to do it there?  Although it's usually used in RNN settings, it is general purpose.

**Comment by skaae** [comment]
We can let @f0k or @Benanne decide :)  

I think its RNN specific.

**Comment by craffel** [comment]
I think because it can be used outside of the context of RNNs, it's probably best to do a PR to the main repository.  It's probably best to put as few things as possible in the critical path to getting recurrent layers added to Lasagne, and that PRs should probably cover the minimum amount of code to add the intended functionality.  Plus, more eyes will be on the code if you do a PR there. Same goes for #28 and #31.  If @f0k and @benanne don't want separate PRs, we can do them here, I just don't have a lot of expertise in any of these so I feel somewhat unqualified to audit them.

**Comment by skaae** [comment]
Yes its fine. I'll wait for a reply and move it if necessary.

**Comment by f0k** [comment]
I think a PR against Lasagne would be better. The implementation is very inefficient, though, as it will create copies of the tensors. You should rather compute the squared norms separately and add them up. It would also be good to reuse code of `norm_constraint`, or just generalize that function to optionally accept a list of tensors instead of a single tensor, and to optionally return the norms or scaling factors (if that's absolutely needed).

**Comment by benanne** [comment]
Not too sure about merging it with `norm_constraint`, we risk ending up with monolithic functions that try to do everything and support every possible use case, which leads to code that's very hard to read and understand. I'd take a bit of code duplication over that any day.

**Comment by f0k** [comment]
Ah yes, and #28 and #31 should also become PRs against Lasagne instead, those layers could be useful independently of RNNs.

**Comment by skaae** [comment]
I copied most of it from pylearn. I rewrote the code. I'll move the PR to lasagne.

**Comment by skaae** [comment]
Moved to https://github.com/Lasagne/Lasagne/pull/253

**Pull request closed without merging**
