### PR TITLE
attempt to make `mask` optional in `CustomRecurrentLayer.get_output_for()`

### PR DESCRIPTION
**Pull request by JackKelly**
Hi there.  This is my quick attempt to make `mask` optional in `CustomRecurrentLayer.get_output_for()`.  I'm not 100% confident I've done this correctly but it appears to work for me.  (this time I've also attempted to cherry-pick the relevant commit)

### CODE REVIEW

**Comment by craffel** [comment]
Oh, good call!  Don't know why I missed this.  Do you mind making it more like the changes I made to `LSTMLayer` here?
https://github.com/craffel/nntools/commit/5f1cc449503c6656c8db1212a92bb8f680a51618#diff-48f9f9d93ed00587a6c49197b4d6e64e
Specifically, moving the `mask.dumshuffle` line within the lower `if self.backwards and mask is not None` statement, so we only have to have one statement like that.  And, extending the docstring if you're up for it.  I'm not sure why I changed `step_back` to `step_masked` but you can do that too if you want!

**Comment by JackKelly** [comment]
Sure thing, I'll get this done next week (I'm away from my computer this
weekend).

**Comment by JackKelly** [comment]
Sorry it took me a while to make these changes!  I've finished now and the code appears to run fine for me.

**Comment by craffel** [comment]
Looks good to me, merging, tanks!

**Pull request merged**
