### PR TITLE
Lstm canges

### PR DESCRIPTION
**Pull request by skaae**
Changes the LSTM cell to be calculated using stacked matices. I used the T.stack to stack weight and biases into symbolic variables that are then used in the LSTM calculations.  I have switched to the modulation_gate naming, and added a reference to http://arxiv.org/abs/1409.2329.

I have added test values to the test and enabled peepholes.

### CODE REVIEW

**Comment by craffel** [comment]
Thanks for this.  Some comments- 
- AFAIK test values don't work with `scan`, see the note at the end of the section [here](http://deeplearning.net/software/theano/tutorial/debug_faq.html#using-test-values).  Is that note out of date?
- Is there any reason you changed to `modulationgate` from `cell` apart from personal taste?  As far as I know, "input modulation gate" is much less common than "cell".  If we're going to use the terminology from the Zaremba paper, it would need to be called `inputmodulationgate` (or `inmodgate`); the term "modulation gate" doesn't make sense and doesn't appear anywhere in the paper.
- It would probably be worth checking whether using `T.concatenate` slows it down at all; the [short code snippet I posted](https://github.com/benanne/Lasagne/issues/17#issuecomment-70015915) doesn't include gradients/updates which I suppose could be slower. Did you check this already?
- I've been spending some time yesterday and today trying to figure out why the code got 3 times slower after changing to the `backwards` flag.  I'd like to wait to merge this pull request until that's resolved, if that's OK with you.  Let me know if there's some other deadline which means this should be merged sooner.

Otherwise looks good to me.

**Comment by skaae** [comment]
On 15 Jan 2015, at 21:08, Colin Raffel notifications@github.com wrote:

> Thanks for this. Some comments-
> 
> AFAIK test values don't work with scan, see the note at the end of the section here. Is that note out of date?
> I’m nearly sure that they work with scan, I noticed that they do not work with random streams, e.g. in dropout. It usually gives you the line number of the error which speeds up debugging.
> 
> Is there any reason you changed to modulationgate from cell apart from personal taste? As far as I know, "input modulation gate" is much less common than "cell". If we're going to use the terminology from the Zaremba paper, it would need to be called inputmodulationgate (or inmodgate); the term "modulation gate" doesn't make sense and doesn't appear anywhere in the paper.
> No, it I find i easier to read and understand. But if you prefer Cell, feel free to change it. 
> It would probably be worth checking whether using T.concatenate slows it down at all; the short code snippet I posted doesn't include gradients/updates which I suppose could be slower. Did you check this already?
> No i haven’t done any speed comparisons, how fast did the code run before? I had an (to me) unexplainable speed drop a few days ago, I had to roll back on github to solve it.
> I've been spending some time yesterday and today trying to figure out why the code got 3 times slower after changing to the backwards flag. I'd like to wait to merge this pull request until that's resolved, if that's OK with you. Let me know if there's some other deadline which means this should be merged sooner.
> If for some reason scan is slow when it goes backwards we could just flip the input and the mask, I guess that would work.

Have you tried profiling the code and noticed any differences?

I don’t have any deadlines. I’ll just use my own fork until it’s merged. I published my fork because I got an email from someone who wanted to use the code.

**Comment by craffel** [comment]
> I’m nearly sure that they work with scan, I noticed that they do not work with random streams, e.g. in dropout. It usually gives you the line number of the error which speeds up debugging.

Hmm, this is good to know.

> No i haven’t done any speed comparisons, how fast did the code run before? I had an (to me) unexplainable speed drop a few days ago, I had to roll back on github to solve it.

On [my benchmark](https://github.com/craffel/lstm_benchmarks), it was running at 75 seconds per epoch on my machine; after changing to the backwards flag, it was up to around 210 seconds per epoch.  The reason I want to wait is that these changes should speed things up and I don't want to confound speed decreases caused by past stuff with increases caused by this stuff.

> Have you tried profiling the code and noticed any differences?

That's what I'm doing now.

**Comment by craffel** [comment]
Merged.  Surprisingly the LSTM benchmark is a little slower with these changes than it was before, which I will investigate.

**Pull request closed without merging**
