### PR TITLE
add reshape example to recurrent

### PR DESCRIPTION
**Pull request by skaae**
Add reshape example to recurrent.py

I inserted a linebreak in line 450 which was too long.

### CODE REVIEW

**Comment by craffel** [comment]
Thanks for this.  I'd actually prefer the example to be the absolute minimum to demonstrate what we're trying to show, i.e. that you can mix recurrent layers with dense layers.  This example also shows some other stuff, like how to use `T.nnet.cross_entropy` (worth noting that Lasagne now has it's own cross-entropy objective), getting parameters, computing updates, creating a Theano function, forward/backward layers, etc. which should all probably go into a different, more fleshed-out example.   I think it should be simplified to

```
>>> from lasagne.layers import *
>>> import lasagne
>>> import theano.tensor as T
>>> x = T.tensor3()
>>> batchsize, seqlen, _ = x.shape   
>>> num_inputs, num_units, num_classes = 10, 12, 5
>>> l_inp = InputLayer((None, None, num_inputs))
>>> l_lstm = LSTMLayer(l_inp, num_units=num_units)
>>> l_shp1 = ReshapeLayer(l_lstm, (-1, num_units))
>>> l_softmax = DenseLayer(l_shp1, num_units=num_classes)
>>> l_out = ReshapeLayer(l_softmax, (batchsize, seqlen, num_classes))
```

There should also probably be tons more comments to make it clear what's going on, but I can add those.

**Comment by skaae** [comment]
Both is fine with me.  I'll simplify the example.

**Comment by skaae** [comment]
The example is now simplified.

**Comment by craffel** [comment]
The example uses `T.tensor3` but there's no `import theano.tensor as T`.  Even better would just be to use `l_inp.input_var` instead.  Also needs a lot more comments.  I will merge now and make those changes myself, just for expediency.

**Pull request merged**
