### PR TITLE
Precompute input

### PR DESCRIPTION
**Pull request by JackKelly**
An implementation of the speedup technique suggested in issue #20.  Have not yet implemented this for LSTMLayer.

### CODE REVIEW

**Comment by craffel** [comment]
Thanks for this!  A few things:
- I don't think the memory usage will be 4x higher for the recurrent/custom recurrent layers, only for the `LSTMLayer`.  It should be ~2x for recurrent/custom recurrent.  Can you verify this?
- `precompute_input` should default to `False`, I think - it's bad to have a default option where if you change its value (`gradient_steps`) to something which should work (not the default, `-1`), you get an error.  I would potentially be comfortable with it later on, esp until we get a handle on the additional memory requirements and speedup.  Do you agree?  Worth deciding this because currently, we precompute the input without the kwarg flag in `LSTMLayer`; we should make the call signature and behavior similar across layers.
- Don't you need to pass the `precompute_input` kwarg to `super` here? https://github.com/craffel/nntools/pull/25/files#diff-48f9f9d93ed00587a6c49197b4d6e64eL225

**Comment by craffel** [comment]
Precomputing input is now included as of #27, but there are no arguments for controlling whether to precompute or not.  @JackKelly do you want to rebase and add the logic you originally wrote for whether to precompute the input or not?

**Comment by JackKelly** [comment]
@craffel sorry for being slow on this.  Lots of other work on at the moment.  I will rebase and add my logic ASAP (hopefully within a week)

**Comment by JackKelly** [comment]
@craffel Hmmm, rebasing is looking pretty damn hairy (although this could be because I'm not especially experienced at rebasing).  I'm coming to the conclusion that it will be far less work if I just close this PR; delete my fork of your code, re-fork your code; manually re-apply my changes (in a new branch) and finally create a new PR.  Does that plan work for you or will that break stuff at your end?

**Comment by craffel** [comment]
Yes, that's probably easiest for you if you're willing to do that, although you don't need to create a new PR - just create a new branch based on craffel:recurrent, apply your changes there, and modify this PR to point to your new branch instead of JackKelly:speedup_issue20.

**Comment by JackKelly** [comment]
Hmm, I can't see how to modify this PR to point to my new branch (I think github has become confused since I deleted my original fork!).  So I'll close this PR.  Sorry this is getting a little complicated!

**Pull request closed without merging**
