### PR TITLE
Allow hid_to_hid to have a bias vector.

### PR DESCRIPTION
**Pull request by JackKelly**
For example, Le et al 2015 allow hid_to_hid to have a bias
vector (which they init to 0).

Le, Jaitly, Hinton, "A Simple Way to Initialize Recurrent
Networks of Rectified Linear Units" (2015)
http://arxiv.org/abs/1504.00941

Perhaps the default behaviour should be to set `b_hid_to_hid=None` to maintain backwards compatibility with the old code.  Not sure what's best to do here.  And, I must admit, I have no strong intuition for what the 'usual' convention is regarding allowing hid_to_hid to have a bias vector.

### CODE REVIEW

**Comment by craffel** [comment]
Can you point me to where in that paper they say that the hidden-to-hidden connection has a bias vector?  I'm not seeing it.  The reason only `in_to_hid` is given a bias vector is that the RNN's output is computed as 

```
output = nonlinearity(dot(W_in_to_hid, input) + dot(W_hid_to_hid, previous_hidden) + bias))
```

In the `CustomRecurrentLayer`, the dot products are computed by the supplied layers.  Note that if there's one bias it doesn't really matter which layer has the bias.  If both layers supply a bias, the output equation would be

```
output = nonlinearity(dot(W_in_to_hid, input) + dot(W_hid_to_hid, previous_hidden) + bias_in_to_hid + bias_hid_to_hid))
```

Both bias terms do exactly the same thing; there's really no advantage (as far as I can tell) to having both of them, so that's why we only have one.

**Comment by JackKelly** [comment]
> Can you point me to where in that paper they say that the hidden-to-hidden connection has a bias vector?

On page 2, at the start of the 2nd paragraph under "The initialization trick" they write _"We initialize the recurrent weight matrix to be the identity matrix and biases to be zero."_  It's entirely possible that I've misunderstood them and by "biases to be zero" they mean "no biases".

> Both bias terms do exactly the same thing; there's really no advantage (as far as I can tell) to having both of them, so that's why we only have one.

Excellent point!  Now you've explained it it's crystal clear that there should be only one bias.  Sorry!

**Comment by craffel** [comment]
> they write "We initialize the recurrent weight matrix to be the identity matrix and biases to be zero." It's entirely possible that I've misunderstood them and by "biases to be zero" they mean "no biases".

Ah, I assumed that they meant "The biases of all of our networks", or even "The entries of the bias vector".

> Excellent point! Now you've explained it it's crystal clear that there should be only one bias. Sorry!

Glad it makes sense - thanks for bringing this up either way.

**Comment by JackKelly** [comment]
> I assumed that they meant "The biases of all of our networks", or even "The entries of the bias vector".

Yeah, on re-reading it, I see that they meant "We initialize the [recurrent weight matrix to be the identity matrix] and [biases to be zero]" not "We initialize the recurrent... biases to be zero".  If that makes sense!

**Pull request closed without merging**
