### PR TITLE
add embedding layer

### PR DESCRIPTION
**Pull request by skaae**

### CODE REVIEW

**Comment by craffel** [comment]
This seems pretty application-specific to NLP stuff.  I'm not really familiar with how this is used.  Maybe it would fit better in some example code for a tutorial on creating special Lasagne layers? Or an NLP tutorial?

**Comment by skaae** [comment]
I think it is a common type of layer. You use it is an alternative to one-hot encoding your input. In NLP i think this is a lot faster because the vocabolary might be large (10k-100k) and then it is a lot faster to do look up instead of dot products. 

You also use it with Word2Vec/Gloove etc.

I will write an Penn tree bank tutorial where i need this layer. In the tutorial i'll try to reproduce 
http://arxiv.org/abs/1409.2329

**Comment by benanne** [comment]
This is definitely useful for a lot of things :) I've been meaning to add something like this anyway.

**Comment by skaae** [comment]
Should i move the PR to lasagne?

**Comment by benanne** [comment]
Go for it :)

**Comment by skaae** [comment]
Moved to https://github.com/Lasagne/Lasagne/pull/254

**Pull request closed without merging**
