### PR TITLE
scan unroll argument

### PR DESCRIPTION
**Pull request by skaae**
Adds scan_unroll argument to recurrent functions.
- scan_unroll is added to utils.py
- Adds tests that tests if the output from unrolled graph and theano.scan are equal

### CODE REVIEW

**Comment by skaae** [comment]
@craffel : How do i update the pull request to the new master? Can i just do 

`git  pull craffel/master` and then resolve the conflicts? 

Not a git expert yet :)

**Comment by craffel** [comment]
Best course of action is to do

```
git fetch upstream
git rebase upstream/master
```

assuming that craffel/nntools is your upstream!  If you do `git remote -v` you should see

```
upstream    https://github.com/craffel/nntools.git (fetch)
upstream    https://github.com/craffel/nntools.git (push)
```

**Comment by skaae** [comment]
awesome. Tried it here: https://github.com/craffel/nntools/pull/32.

I'll update this PR aswell.

**Comment by skaae** [comment]
Moved to https://github.com/craffel/nntools/pull/40

**Pull request closed without merging**
